[ko]
rust = "러스트"
build = "빌드"
cargo = "Cargo"
mdbook = "mdBook"
crait = "크레이트"

[ko-suffix]
suffix = [ # 왼쪽은 받침이 없을때, 오른쪽은 받침이 있을때
    ["는", "은"],
    ["가", "이"],
    ["를", "을"],
    ["로", "으로"],
    ["로서", "으로서"],
    ["의", "의"],
    ["에서", "에서"],
    ["에서는", "에서는"],
]